### ISSUE TITLE
onEnd is not fired on partially downloaded base64 encoded audio when html5 is enabled

### ISSUE THREAD

**Issue by crlssn** [thangngoc89/react-howler#45] opened 2017-07-24 13:26 UTC
I'm preloading a partially downloaded audio file, encoding it in base64 and then playing it through Howler. It plays fine, but the `onEnd` method is not fired once the audio has ended. (Setting `html5` to `false` fixes it, but it will make the web page crash on iOS instead.) The reason why `onEnd` doesn't fire I suspect is because it assumes the duration of the full audio file and not the partially downloaded one.

I'm not sure if this is a bug for react-howler, howlerjs or if it's an inherit bug from the WebAudioAPI itself.

[Link to base64 encoded audio for testing purposes.](https://paste.ubuntu.com/25162626/)

**Comment by crlssn** [comment] 2017-07-24 18:04
Update: Setting `html5` to `false` does not fix it in Safari (tested in both desktop and mobile), it does fix it in Chrome however. It does not make the web page crash in iOS either - I think that was a different issue which occurred when I generated the base64 data client side instead of server side which I'm doing now.

**Comment by Stenerson** [comment] 2017-07-24 20:11
Hi @crlssn, thanks for reporting. 
 
My hunch is that this is a howler.js issue. Could you try to reproduce in JSBin using just howler? You can use [this bin](http://jsbin.com/xajoxat/edit?js,console,output) as a starting point. The base64 data you provided makes the bin too large to save but you can paste it in and change the source to play it. 

Both sounds seem to be working for me in Chrome in that bin. Is that what you're seeing too? In Safari (desktop) I can see that `onend` is being called for the test mp3 sound and it appears as though it's not being called for the base64 sound. **However, it actually is called (for me at least) about 1:20 after the sound has finished playing.** I'm not sure why this is and I don't have time to look right now but maybe that discovery will help?

If this reproduces what you're seeing or if you can reproduce directly with Howler I'd suggest opening an issue [there](https://github.com/goldfire/howler.js/issues). If you can't reproduce in Howler can you share some react code so I can try to reproduce locally? 

Please let me know - Thanks!

**Comment by Stenerson** [comment] 2017-09-03 12:32
Hi @crlssn, any update on this? I’m thinking about closing since there’s nothing actionable at this point but wanted to check with you first. Thanks!

**Comment by crlssn** [comment] 2017-09-03 12:37
Sorry, yes you can close this issue. We decided on a different approach for now. Thank you though, and great work on this package! 

> However, it actually is called (for me at least) about 1:20 after the sound has finished playing.

This happens for me to, but since the new file only was a few seconds long this was not feasible. I would guess that i somehow reads the meta data instead of the content.

**Closed** 2017-09-03 12:39 UTC
